php-memcached-dev/php-memcached

- php_memcached.c
Foreign serializers like msgpack and igbinary may crash on randomly initialized zval because they check of IS_ARRAY, IS_OBJECT (or any type) on certain circumstances.
> Fix crashes with foreign serializers

- php_libmemcached_compat.c
- php_memcached.c
- php_memcached.h
- php_memcached_session.c
- tests/version.phpt
Fix a number of PHP 7-related issues. Still a bunch of failing tests though.
> More tests pass now

- php_memcached.c
- php_memcached.h
This should bring things up to date with current PHP 7
> Update a few PHP 7 issues

- php_memcached_session.c
Fix for the https://github.com/php-memcached-dev/php-memcached/issues/196
> check if session was allocated on PS_OPEN_FUNC

- php_memcached.c
Fairly straight forward. Was building with igbinary and tripped on this.
> removing unused var, fixing smart_str use w/ igbinary

- php_memcached_session.c
- php_memcached_session.h
- tests/session_basic2.phpt
- tests/session_basic3.phpt
This patch adopts new session save handler definition that supports "lazy_write" which omit needless writes when session data is not changed. This save handler also supports "use_strict_mode" which prevents classic session adoption and never has session ID collisions.
> Use new session save handler

- php_memcached_session.c
php7 branch does not contain a fix of #144.
If expiration time is short, it is affected by the problem reported in #144. So, expiration time should be specified in the relative number of seconds.
But expiration time is greater than 30 days, it must be specified by unix time.
> fix expiration

- php_memcached_session.c
This simply adds in the "usual" `#if HAVE_MEMCACHED_SASL` constraint around a call to `memcached_destroy_sasl_auth_data`. I think you simply overlooked this one with all the other changes.
Should also fix #217 - I only tested on Alpine Linux 3.3 though.
> Adds a missed SASL presence constraint

- ChangeLog
- package.xml
Prerequisite for further work on #213; please merge to master and then also PHP 7 branch, I'll continue on PHP 7 changelog entries later.
Should I convert the whole changelog to markdown syntax and give it a `.md` extension? If so, then I'll add that change to this PR here, just let me know.
> Fix changelog with missing releases and all dates

- memcached.ini
This updates some of the memcached.ini documentation settings
to reflect the default ini settings used in php_memcached.c.
Some new settings were added, and other settings had changes to their defaults.
There are other new/updated settings, which can be changed in other PRs.
I not completely certain of what memcached.server_failure_limit does and why it would be overriden, and http://docs.libmemcached.org/memcached_behavior.html#MEMCACHED_BEHAVIOR_REMOVE_FAILED_SERVERS says that  MEMCACHED_BEHAVIOR_SERVER_FAILURE_LIMIT was deprecated, so I'd prefer it if a contributor documented that setting outside of this PR.
For issue #233
> Document miscellaneous ini settings and new defaults for PHP7 release

- memcached.ini
This documents memcached.default_consistent_hash, default_binary_protocol, and
default_connect_timeout, for the php7 release
Any comments on wording/structure of comments? Is anything inaccurate/missing?
For issue #233
> [php7] Document ini settings for the default memcached connection configs

- php_memcached.c
a potential bug is introduced in https://github.com/php-memcached-dev/php-memcached/commit/dc5b22a8dace7373c1ef9d2946e89a660ed35b20#diff-f76062ebbcf30f0491af9ca937d17762R3270
the null-termination is missed during conversion; while zend_string_init did it correctly
https://github.com/php/php-src/blob/master/Zend/zend_string.h#L156
potential fix for #250 
-----
credit: thanks to my colleague @yuripave isolate the issue to the abovementioned commit. it makes further analysis much easier
> fix #250: non-null-terminated zend_string in s_decompress_value

- php_memcached.c
- tests/incrdecr.phpt
Check the existence of an error, and only then if it is the maximum value.
Fix for #243
> Fix #243: Increment/decrement of an undefined key returns false with RES_SUCCESS

- php_memcached.c
- tests/keys.phpt
The current validation for the object keys is not complying with the [protocol specification](https://github.com/memcached/memcached/blob/master/doc/protocol.txt#L41) from memcached.
This PR aims at fixing this.
> Fix object key validation

- .travis/travis.sh
igbinary7 was moved to src/php7 of igbinary, and bug fixes/improvements were/will be added there later.
See https://github.com/igbinary/igbinary/pull/62
> Igbinary php7 development is in igbinary/igbinary master branch now

- memcached.ini
- php_memcached.c
And remove a TODO found in the code for allowing users to configure
whether or not to use binary protocols for sessions.
If there are any comments on formatting, what the comment for memcached.sess_binary_protocol should say, etc., I'll change my PR to address them.
For issue #233
> Document memcached.sess_binary_protocol

- package.xml
- php_memcached.c
- tests/reset_keyprefix.phpt
- ZSTR_VAL(str) == 0 should be ZSTR_LEN(str) == 0
> Cannot reset OPT_PREFIX_KEY #293

- memcached-api.php
- package.xml
And update the memcached-api.php file for the branch.
> Add release notes about session protocol, get and getMulti changing

- .travis.yml
- package.xml
- tests/invoke_callback_2.phpt
- tests/session_lock-php71.phpt
invoke_callback_2 fails because of ArgumentCountException (init_cb_arg gets only 2 args).
Check number of passed arguments with func_num_args() insteadof checking $args is null
session_lock fails because of second warning in 7.1
Skip session_lock.phpt for php < 7.1 and create new testcase for >= 7.1 which tests both warnings.
> Fix tests for PHP 7.1

- memcached-api.php
- php_memcached.c
Added one optional parameter type for method 'getStats'.
Example:
```
<?php
$m = new Memcached();
$m->addServer('localhost', 11211);
$r = $m->getStats();
var_dump($r);
$r = $m->getStats('settings');
var_dump($r);
```
( Old PR #264 )
> Add optional parameter 'type' for method 'getStats'

- php_memcached_session.c
It seems that zend_ini_long doesn't work anymore with ZEND_STRS
and that the extension should use ZEND_STRL, back again.
We inspected and stumbled upon this issue when some session had their lock stuck. It seems that the extension was unable to retrieve the INI value for max_execution_time.
This was at some point changed to ZEND_STRS - but it seems that now it has to use ZEND_STRL.
Anyone can probably easily test this and confirm that it is indeed an issue and that this fixes it.
> 0 max_execution_time ini value

- php_memcached_session.c
This is a replacement for pull request #165
>  Added error reporting to session code

- php_memcached.c
the condition to do compression is incorrent since previous refactoring. according to docs
https://secure.php.net/manual/en/memcached.configuration.php#ini.memcached.compression-factor
> Store **compressed** if: plain_len > comp_len * factor
https://github.com/php-memcached-dev/php-memcached/blob/master/memcached.ini#L93
> store **compressed** if: plain_len > comp_len * factor
hence, the condition (to early exit, without compression) should be
`if (ZSTR_LEN(payload) < (compressed_size * compression_factor))`
------
PR includes
- fix to the compression_factor formula (whether to compress or not),
- correctly unset MEMC_VAL_COMPRESSION_{FASTLZ,ZLIB} flags flags properly when plain-text is sent
> fix: compression edge case

- package.xml
- php_memcached.c
- tests/compression_conditions.phpt
This PR includes the tests from #256 with code changes to handle compression failure and uncompressable data without bombing out. My assumption is that the user application would prefer that its data end up in memcached compressed _if possible_ but just as well uncompressed if it ends up that way, which is better than not storing the data.
> Compression conditions adjustments

- php_memcached.c
- tests/incrdecr.phpt
- tests/incrdecr_bykey.phpt
> Support for 64-bit increments and decrements

- php_memcached.c
Allows getAllKeys() to work with newer memcached servers. Caveats: will drop some non-deterministic number of keys from the output in a multi-server configuration.
Fixes #203
> Ignore specific errors from memcached_dump for getAllKeys()

- tests/gh_90.phpt
- tests/incrdecr.phpt
- tests/incrdecr_bykey.phpt
On both i386 and x86_64
```
=====================================================================
TEST RESULT SUMMARY
---------------------------------------------------------------------
Exts skipped    :    0
Exts tested     :   18
---------------------------------------------------------------------
Number of tests :   81                78
Tests skipped   :    3 (  3.7%) --------
Tests warned    :    0 (  0.0%) (  0.0%)
Tests failed    :    0 (  0.0%) (  0.0%)
Expected fail   :    1 (  1.2%) (  1.3%)
Tests passed    :   77 ( 95.1%) ( 98.7%)
---------------------------------------------------------------------
Time taken      :   39 seconds
=====================================================================
```
> ensure tests are ok for 32bits build

- package.xml
- tests/incrdecr_64.phpt
> Separate test for 64-bit increment/decrement/incrementByKey/decrementByKey

- package.xml
- php_libmemcached_compat.c
- php_libmemcached_compat.h
- php_memcached.c
- php_memcached_session.c
- tests/gh_155.phpt
- tests/session_basic.phpt
- tests/session_basic2.phpt
- tests/session_basic3.phpt
- tests/session_lazy_warning.phpt
- tests/session_lock-php71.phpt
- tests/session_lock.phpt
- tests/touch_binary.phpt
Resolves #310 by letting the user know how to fix the problem.
> Update warning for touch command in binary protocol mode with libmemcached < 1.0.18

- php_memcached.c
just to make gcc happy
1/ variable « memc_user_data » set but not used [-Wunused-but-set-variable]
(void)memc_user_data only to avoid the warning (removed later by optimizer)
Another solution (but probably a bit ugly) is to have 1 set of macros without data, and 1 set with.
2/  « status » may be used uninitialized in this function [-Wmaybe-uninitialized]
3/ pointer targets in passing argument 2 of « smart_str_appendl_ex » differ in signedness [-Wpointer-sign]
> Fix build warnings

- php_memcached.c
[type](https://github.com/php-memcached-dev/php-memcached/pull/298) is optional, but `ReflectionParameter::isOptional()` returns `false`.
```php
$method = new \ReflectionMethod(new \Memcached(), 'getStats');
foreach ($method->getParameters() as $p) {
var_dump($p->name, $p->isOptional());
}
```
```
string(4) "args"
bool(false)
```
```
string(4) "type"
bool(true)
```
> Fix optional parameter getStats($type)

- memcached-api.php
This PR isn't complete, some constants (e.g. `Memcached::ON_*`) are
still not documented.
It aims to fill in commonly used constants.
> Document GET_EXTENDED flag. Add/rename other missing/misnamed constants.

- memcached.ini
- php_memcached.c
1st commit is mostly cleanup, follow php practice, but needed by the second one
2nd commit is another way to (try to) improve user experience with older libmemcached version and avoid the warning about using touch (which can be confusing) => for discussion.
> Refresh memcached.ini and set sess_binary_protocol off by default with older libmemcached

- php_memcached_session.c
The defines MEMC_SESS_DEFAULT_LOCK_WAIT and MEMC_SESS_LOCK_EXPIRATION are not in use anymore.
> Remove unused defines

- php_memcached_session.c
> Fix session persistence by checking memcached behavior values before setting

- config.m4
> The configure script warns if libmemcached needs sasl.h

- config.m4
- memcached-api.php
- package.xml
- php_memcached.c
- tests/set_encoding_key.phpt
- tests/set_encoding_key2.phpt
> Add support for libmemcached encryption

- .travis.yml
- php_memcached.c
- php_memcached_private.h
- php_memcached_session.c
> Update for new PHP 7.3 REFCOUNT macros

- memcached.ini
- php_memcached.c
- php_memcached.h
- php_memcached_private.h
- php_memcached_session.c
> Add INI setting to choose session consistent hash (ketama or ketama_weighted)

- config.m4
The -lpthread option has been added long time ago in commit
c10de3699faa3ecb4cb6861d6c92157e0c7e18ce
and has been since also refactored and therefore comment is not needed anymore:
feed35e22040b874ba6fc8659dc16b498e6e4150
Thanks for considering merging this or checking it out...
> Remove forgotten unused comment about -lpthread

- .gitignore
The configure.ac is used since PHP 7.2 and the updated build system instead of the old configure.in file which is still used in PHP 7.1 and lower versions.
These files are generated during the phpize...
Thank you.
> Add configure.ac to Git ignored files

- config.m4
Hello, Autoconf made several macros obsolete in several versions behind very long time ago, including the `AC_TRY_COMPILE` which should be replaced with current `AC_COMPILE_IFELSE` instead.
Refs:
* Autoconf changelog: http://git.savannah.gnu.org/cgit/autoconf.git/tree/ChangeLog.3
* Autoconf docs: https://www.gnu.org/software/autoconf/manual/autoconf-2.69/html_node/Obsolete-Macros.html
This patch has been done with the help of `autoupdate` script:
```bash
autoupdate config.m4
```
Thanks for considering checking this out or merging it.
> Replace obsolete macros AC_TRY_FOO with AC_FOO_IFELSE

- php_memcached.c
```
/work/GIT/php-memcached/php_memcached.c: In function 's_stat_execute_cb':
/work/GIT/php-memcached/php_memcached.c:2755:27: warning: field precision specifier '.*' expects argument of type 'int', but argument 4 has type 'size_t' {aka 'long unsigned int'} [-Wformat=]
spprintf (&buffer, 0, "%.*s", value_length, value);
~~^~   ~~~~~~~~~~~~
```
> fix build warning

- php_memcached.c
Set retval to false so that the resulting uninitialized zval won't be
used.
> Fix segfault for unknown memcache flags

- memcached.ini
The documented default was 200, while in reality it seems this is actually set to 5. While 5 is arguably on the low side, at least have the documentation in sync with reality.
See here: https://github.com/php-memcached-dev/php-memcached/blob/e7ac9225abd0f6660927fa89585634caf4a76f44/php_memcached.c#L374
> Update documented default for sess_lock_retries

- .travis/travis.sh
- php_memcached_session.c
This macro was defined empty in PHP 7.x, and removed in PHP 8.x.
Resolves #443
> Remove stray instances of TSRMLS_CC macro

- php_memcached.c
Build error on FreeBSD with PHP 7.4 RC6:
```
--- php_memcached.lo ---
/wrkdirs/usr/ports/databases/pecl-memcached/work-php74/memcached-3.1.4/php_memcached.c:3237:7: error: expected ';' after expression
ulong key_index;
^
;
/wrkdirs/usr/ports/databases/pecl-memcached/work-php74/memcached-3.1.4/php_memcached.c:3237:2: error: use of undeclared identifier 'ulong'
ulong key_index;
^
/wrkdirs/usr/ports/databases/pecl-memcached/work-php74/memcached-3.1.4/php_memcached.c:3237:8: error: use of undeclared identifier 'key_index'
ulong key_index;
^
/wrkdirs/usr/ports/databases/pecl-memcached/work-php74/memcached-3.1.4/php_memcached.c:3250:49: error: use of undeclared identifier 'key_index'
ZEND_HASH_FOREACH_KEY_VAL(Z_ARRVAL_P(options), key_index, key, value) {
^ …
```
> Fix build with PHP 7.4

- .travis.yml
Removing `snapshot` ensures the latest version of PHP 7.4.x is always used. `7.4snapshot` seems to have been stuck on `7.4.3-dev` (see [latest build output](https://travis-ci.org/github/php-memcached-dev/php-memcached/jobs/661023934)).
> PHP 7.4 is no longer in "snapshot"

- php_memcached_server.c
no_separation removed on php 8.0
> fix build for php 8.0

- package.xml
- php_memcached.c
- php_memcached.stub.php
- php_memcached_arginfo.h
- php_memcached_legacy_arginfo.h
- tests/bad_construct.phpt
- tests/bad_construct_8.phpt
- tests/expire.phpt
- tests/undefined_set.phpt
- tests/vbucket.phpt
- tests/vbucket_error_7.phpt
- tests/vbucket_error_8.phpt
Pros:
* Take benefit of PHP 8 feature, easier to maintain a simple stub file
* Generate both arginfo for PHP 7 and PHP 8
Cons:
* Requires (php 8-master or >= RC2) to generate (but not needed at build/runtime)
* Lost some type hinting (array) introduce in previous versions
> generate arginfo from stub for PHP 7 and 8

- memcached.ini
Fix a small typo.
`memcached.use_sasl` config name [seems not used](https://github.com/php-memcached-dev/php-memcached/blob/ed3f39d07e08517e68acdbf57304da1328d7adac/php_memcached_session.c#L226) anymore.
> Fix memcached.ini comment - remove reference to old config name (#456)

- php_memcached.c
libmemcached would close all connections if the option(like MEMCACHED_BEHAVIOR_BINARY_PROTOCOL) was set, even though the value wasn't modified. If the user uses the setOptions in the wrong way may cause the persistent connection never works.
> MOD: don't re-set the libmemcached option if not modified

- php_memcached.c
- tests/bad_construct_8.phpt
For consistency with other PHP 8 extensions.
> promote error "Memcached constructor was not called" to exception

- php_memcached.stub.php
- php_memcached_arginfo.h
- php_memcached_legacy_arginfo.h
A few fixes for stub/arginfo to match the reality, which makes the test suite complete successfully on PHP-8.0
> fix php8 arginfo

- .travis.yml
This will be separate from the `master` entry, which will always be tracking the next version.
> Add PHP 8.0 to the Travis CI matrix

- tests/expire.phpt
The issue reported in https://code.google.com/archive/p/memcached/issues/275 was fixed more than 8 years ago and the test is no longer expected to fail
> Don't expect tests/expire to fail

- tests/undefined_set.phpt
1st commit fix bad param count raising funny message
`Fatal error: Uncaught TypeError: Memcached::setMulti(): Argument #2 ($expiration) **must be of type int, int given** in `/work/GIT/pecl-and-ext/memcached/tests/cas_multi.php:14````
2nd hides deprecation warning
> Fix issue raised by PHP 8.1

- php_memcached.c
- tests/experimental/setmulti_badserialize.phpt
This was introduced in https://github.com/php-memcached-dev/php-memcached/commit/6837d89494, pull https://github.com/php-memcached-dev/php-memcached/pull/214. I suspect it may have been a left-over from debugging something. The test was later changed in 6837d89494 to expect the warning in question, although other similar tests don't encounter such warning currently.
It appears no other Memcached methods emit a PHP Warning when they encounter a write read or failure. Instead, they typically turn their return value into boolean false, and provide details via getResultMessage().
The introduction of this warning since php-memcached 3.0 has led to a number of confused consumers (locally #260, #409, #450, and more reports within downstream issue trackers).
Closes …
> Remove "failed to set key" warning from setMulti

- memcached.ini
- php_memcached.c
It's wired that store commands would be auto-retry implicitly while the default value of store_retry_count was 2, as well as the timeout, would be 3 times in those store commands which may confuse users. IMHO, the retry should be set explicitly instead of implicitly.
> FIX: store_retry_count shouldn't be set implicitly

- .github/workflows/build-and-test.yml
Given that PHP 8.1 will be released within 2 weeks I think it's good to fail instead of skip.
Added PHP 8.2 as experimental :)
> Remove experimental for PHP 8.1 and add PHP 8.2 experimental

- config.w32
The Windows SDK does not define `ssize_t`, so libmemcached does not
define `HAVE_SSIZE_T`.  However, PHP's config.w32.h has
`#define ssize_t SSIZE_T`, so building memcached fails.  We fix this by
defining `HAVE_SSIZE_T` via the extension's `CFLAGS`.
> Fix MSVC builds wrt. ssize_t

- config.w32
The memcached library is usually named libmemcached.lib, so we should
check for this name, too.
> Adhere to standard naming convention of Windows libs for PHP

- php_memcached.c
- php_memcached.stub.php
- php_memcached_arginfo.h
- php_memcached_legacy_arginfo.h
Notice: this imply to use **8.2** to generate arginfo.
> mark password as a sensitive param for 8.2

- .github/workflows/build-windows.yml
For now, only building the extension is supported.
---
I've did that as separate action, but of course it could be merged into the existing action for Linux. And of course, the matrix could be extended regarding the PHP versions; as is, 7.2 up to 8.2 should be supported.
Note that the libmemcached dependency is hard-coded, since cmb69/setup-php-sdk does not yet support fetching PECL dependencies.
Unrelated to this PR: there is no check in config.w32 for zlib; that is no problem for in-tree extension builds, but can be for phpize builds; if desired, I can provide a PR to add that check.
> Add minimal Windows CI

- php_memcached.c
Make it possible to use setOption to set `Memcached::OPT_COMPRESSION_LEVEL` which I had missed in my original zstd PR https://github.com/php-memcached-dev/php-memcached/pull/539
zlib compression was using the default zlib compression level of 6. With this PR it is now possible to choose other levels for zlib as well. I have left the default at 6 so nothing will change for people upgrading unless they explicitly set a different level.
And here is some more bench marking data using php serialized data - https://gist.github.com/rlerdorf/b9bae385446d5a30b65e6e241e34d0a8
From this I think it is clear that fastlz is not really useful at any value size anymore. If you are looking for lightning quick compression and decompression, zstd at level 1 is generally a better choice.
I did not apply the …
> Make the compression_level at settable option and expand it to zlib

- php_memcached.c
This is now an error (GCC 14 on Fedora 40), and indeed a real problem
```
/builddir/build/BUILD/php-pecl-memcached-3.2.0/NTS/php_memcached.c: In function 's_compress_value':
/builddir/build/BUILD/php-pecl-memcached-3.2.0/NTS/php_memcached.c:903:65: error: passing argument 2 of 'compress' from incompatible pointer type [-Wincompatible-pointer-types]
903 |                         int status = compress((Bytef *) buffer, &compressed_size, (Bytef *) ZSTR_VAL(payload), ZSTR_LEN(payload));
|                                                                 ^~~~~~~~~~~~~~~~
|                                                                 |
|                                                                 size_t * {aka unsigned int *}
In file included from …
```
> Fix incompatible pointer types (32-bit)

- php_memcached.c
- tests/cas_invalid_key.phpt
- tests/delete_bykey.phpt
- tests/get.phpt
- tests/keys_ascii.phpt
libmemcached's key verification is only done if OPT_VERIFY_KEY is enabled. We should honour this setting in the PHP extension as well and not do it automatically.
This addresses https://github.com/php-memcached-dev/php-memcached/issues/546
Note that I am still not completely sold on making this change.
> If client-side verify_key is not enabled, don't check it automatically

- php_memcached.c
The `MEMC_CHECK_KEY` macro meant to make sure keys are valid was not taking a prefix into account when checking the length of the key. This is especially important to get right in case NOREPLY sets are used on a persistent connection because the server will send a parser error back on a long key and the client is not expecting a reply which in turn messes up subsequent requests on this persistent connection.
> The key length check was not taking the prefix into account

- .github/workflows/build-windows.yml
We
* switch to ~~the latest commit~~ <ins>v0.10</ins> of php/setup-php-sdk
* we enable caching
* we switch to downloads.php.net
* we work around the missing libmemcached-vs17
* we enable testing for PHP 8.4 on Windows
> Updates to Windows CI

- php_memcached.c
As `zend_exception_get_default` was removed in 8.5
> use zend_ce_exception
